### ISSUE TITLE
Error during CFL calculation

### ISSUE THREAD

**Issue by maurical** [KChen-lab/MEDALT#2]
Hi, this is really good work!
I've installed and run scTree.py, it produce the MEDALT tree but I do get an error during the CFL calculation. 
Log below:

[1] Visualization MEDALT!
null device 
          1 
[1] LSA segmentation!
[1] Calculating CFL
Error in subCNV[, startIndex] : incorrect number of dimensions
Calls: do.call -> lapply -> lapply -> FUN
Execution halted
Done!

Any Idea on why this is happening and how can be fixed?
Thank you a lot!

Bests

**Comment by Fang0828** [comment]
Hi Maurical,
We have modified the code. Could you please download the source code again and try it? Thanks.
