### ISSUE TITLE
error in LSA segmentation!

### ISSUE THREAD

**Issue by hanlinzhougit** [KChen-lab/MEDALT#5]
Hi, this is a good work. 
When I used MEDALT, i have meet this error.  LOG is as follow:

_[1] Visualization MEDALT!
null device
          1
[1] LSA segmentation!
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  scan() expected 'an integer', got '2148562433'
Calls: eval ... import -> .local -> DataFrame -> read.table -> scan
Execution halted_

"2148562433" this number is at the 3564 line in my input file. And my input file is more than 5k lines.
Then I used the first 3k lines from my input file into a new file, the new file can be worked by MEDALT.

Any Idea on why this is happening and how can be fixed?
Thank you a lot!

Best Regards

**Comment by lshh125** [comment]
Hello,

My guess is that it has nothing to do with the number of lines, but that the maximum integer supported by R is 2147483647 < 2148562433. I'm not sure if there is a quick and clean fix for that, but you might consider dividing all values in your csv by 2 (and round to the nearest integer).

Best
